#!/usr/bin/python3
print("Content-type: text/html\n")
print("<html>")
print("<head>")
print("<title>Hello, CGI</title>")
print("</head>")
print("<body>")
print("<h1>Hello, CGI in Python!</h1>")
print("</body>")
print("</html>")